CREATE TABLE clinic_settings (
    id VARCHAR(40) PRIMARY KEY,
    clinic_name VARCHAR(160) NOT NULL,
    logo_url TEXT,
    address TEXT,
    phone VARCHAR(40),
    email VARCHAR(180),
    currency VARCHAR(8) NOT NULL,
    invoice_prefix VARCHAR(12) NOT NULL,
    google_client_id VARCHAR(240),
    google_redirect_uri VARCHAR(240),
    bakong_account_id VARCHAR(120),
    bakong_merchant_name VARCHAR(160),
    bakong_currency VARCHAR(8) NOT NULL,
    notifications_enabled BOOLEAN NOT NULL DEFAULT TRUE,
    email_notifications BOOLEAN NOT NULL DEFAULT TRUE,
    sms_notifications BOOLEAN NOT NULL DEFAULT FALSE,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO clinic_settings (
    id,
    clinic_name,
    logo_url,
    address,
    phone,
    email,
    currency,
    invoice_prefix,
    google_client_id,
    google_redirect_uri,
    bakong_account_id,
    bakong_merchant_name,
    bakong_currency,
    notifications_enabled,
    email_notifications,
    sms_notifications
) VALUES (
    'DEFAULT',
    'MediFlex Clinic',
    '',
    'Phnom Penh',
    '',
    '',
    'USD',
    'INV',
    '',
    'http://localhost:8080/login/oauth2/code/google',
    'vira_eourn@bkrt',
    'Vira Eourn',
    'USD',
    TRUE,
    TRUE,
    FALSE
) ON CONFLICT (id) DO NOTHING;
